name: yx2

on:

  # 手动执行
  workflow_dispatch:

  # 每 6 小时执行一次
  schedule:
    - cron: "13 05 * * *"


jobs:

  update-dns:

    runs-on: ubuntu-latest

    steps:

      # ======================================================
      # 1. Checkout
      # ======================================================

      - name: Checkout
        uses: actions/checkout@v6


      # ======================================================
      # 2. Python
      # ======================================================

      - name: Setup Python
        uses: actions/setup-python@v6

        with:
          python-version: "3.x"


      # ======================================================
      # 3. 安装 Python
      # ======================================================

      - name: Install dependencies
        run: |

          python -m pip install --upgrade pip

          pip install requests


      # ======================================================
      # 4. 下载 CloudflareST
      # ======================================================

      - name: Download CloudflareST
        run: |

          

          chmod +x CloudflareST

          echo "CloudflareST版本："

          ./CloudflareST -v


      # ======================================================
      # 5. API 并发检测
      #
      # IP源
      #   ↓
      # 443
      #   ↓
      # Worker API
      #   ↓
      # 16并发
      #   ↓
      # ip.txt
      # ======================================================

      - name: 获取IP并API并发检测

        env:

          CHECK_API_URL: ${{ secrets.CHECK_API_URL_TIAN }}
          SOURCE_URL: ${{ secrets.SOURCE_JPTIAN }}
        
        run: |

          set -e

          python prepare_speedtest.py

          echo ""
          echo "=========================================="
          echo "API合格IP数量："
          wc -l ip.txt
          echo "=========================================="

          


      # ======================================================
      # 6. CloudflareST 测速
      #
      # API合格IP
      #      ↓
      # CloudflareST
      #      ↓
      # result.csv
      # ======================================================

      - name: CloudflareST测速

        env:

          TEST_URL: ${{ secrets.TEST_URL }}

        run: |

          set -e

          if [ ! -s ip.txt ]; then

            echo "❌ ip.txt 不存在或为空"

            exit 1

          fi

          echo ""
          echo "=========================================="
          echo "开始 CloudflareST 测速"
          echo "候选IP数量："
          wc -l ip.txt
          echo "=========================================="

          ./CloudflareST \
            -f ip.txt \
            -tp 443 \
            -dn 16 \
            -url "$TEST_URL" \
            -o result.csv

          echo ""
          echo "=========================================="
          echo "CloudflareST 测速完成"
          echo "=========================================="

          if [ ! -s result.csv ]; then

            echo "❌ result.csv 不存在或为空"

            exit 1

          fi

          echo ""
          echo "测速结果："

          #cat result.csv


      # ======================================================
      # 7. 最快3个 + 更新 DNS
      #
      # result.csv
      #      ↓
      # 下载速度排序
      #      ↓
      # TOP 3
      #      ↓
      # 所有 Zone
      # ======================================================

      - name: 选择最快3个并更新DNS

        env:

          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKENQUANBU }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_IDKOOD }}
          
     
        run: |

          set -e

          python update_dns.py


      
