name: Update iphome

on:
  schedule:
    - cron: '37 */12 * * *' # 每12小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas selenium webdriver-manager

    - name: 下载 CloudFlare IP 列表
      run: |
         wget -qO ip.txt https://raw.githubusercontent.com/ymyuuu/IPDB/refs/heads/main/BestProxy/proxy.txt



    - name: Make script executable
      run: chmod +x CloudflareST

    - name: 测速
      env:
        TEST_URL: ${{ secrets.TEST_URL }}  # 如果是敏感数据，使用 secrets.TEST_URL
      run: |
        set -e
         ./CloudflareST -f ip.txt -t 8 -sl 1 -n 300 -dn 15 -dt 10 -tp 443 -url $TEST_URL -tlr 0 
        
    - name: BestCF
      run: |
        python ${{ github.workspace }}/dd-ns.py
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    
