name: Update cloudflare dns

on:
  schedule:
    - cron: '37 1 * * *'  # 每天定时运行
  workflow_dispatch:       # 手动触发支持

jobs:
  update-ip-list:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 下载 CloudFlare IP 列表
      run: |
        wget -qO ip.txt https://raw.githubusercontent.com/ymyuuu/IPDB/refs/heads/main/BestProxy/proxy.txt

    - name: 清洗 IP 列表，只保留合法 IP 地址
      run: |
        python -c "import re
with open('ip.txt', 'r', encoding='utf-8', errors='ignore') as f:
    data = f.read()
ips = re.findall(r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b', data)
def valid(ip):
    return all(0 <= int(part) <= 255 for part in ip.split('.'))
cleaned = sorted(set(filter(valid, ips)))
with open('ip.txt', 'w') as f:
    f.write('\n'.join(cleaned))"

    - name: Make script executable
      run: chmod +x CloudflareST

    - name: 测速
      env:
        TEST_URL: ${{ secrets.TEST_URL }}
      run: |
        set -e
        ./CloudflareST -f ip.txt -t 8 -sl 1 -n 300 -dn 8 -dt 10 -tp 8443 -url $TEST_URL -tlr 0

    - name: BestCF
      run: |
        python ${{ github.workspace }}/dd-ns.py
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Clean up Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0
